# Generated by Django 5.0.1 on 2024-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Famale')], max_length=1, null=True),
        ),
    ]
